# Porta do Servidor
server.port=8000

# Configuração do Banco de Dados H2 (Roda direto na memória RAM)
spring.datasource.url=jdbc:h2:mem:imobiliaria;DB_CLOSE_DELAY=-1;NON_KEYWORDS=KEY,VALUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ativa o painel visual do H2 no navegador (opcional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console